name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode -U -T 1C clean install
    - name: Plugged-in Tests
      run: mvn --batch-mode -f tests/org.eclipse.epsilon.test verify -P plugged
    - name: Full Test Suite
      run: mvn --batch-mode -f tests/org.eclipse.epsilon.test surefire:test -P unit
    - name: Standalone Maven artifacts
      run: mvn --batch-mode -T 1C -f pom-plain.xml compile
    - name: Upload Log
      uses: actions/upload-artifact@v3.1.3
      with:
        name: metadataLog
        path: tests/org.eclipse.epsilon.test/target/work/data/.metadata/.log
